spring:
  profiles:
    active: dev
    include: secret
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB # ?? ??? ?? ??
      max-request-size: ${spring.servlet.multipart.max-file-size}
  datasource:
    url: jdbc:h2:./book_store_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update # DB ??? ????, ?? ?????? ???? ????.
    properties:
      hibernate:
        default_batch_fetch_size: 100 # Lazy ??? ? ? ??? DB?? ???? ???? ?
        format_sql: true # SQL ??? ?? ?? ???
        highlight_sql: true # SQL ??? ?????
        use_sql_comments: true # SQL ??? ???
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
